"""Add user status flags

Revision ID: 669fc426f1a5
Revises: 65b49501b1a2
Create Date: 2026-03-09 08:53:44.711510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '669fc426f1a5'
down_revision: Union[str, None] = '65b49501b1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint('cart_ibfk_1', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.alter_column('orders', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('is_suspended', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_suspended')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_ibfk_1', 'orders', 'products', ['product_id'], ['id'])
    op.alter_column('orders', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_ibfk_1', 'cart', 'products', ['product_id'], ['id'])
    op.alter_column('cart', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
