"""Update user model changes

Revision ID: 71c3b5630fbe
Revises: 68c1ac4ab3d9
Create Date: 2026-03-09 18:51:31.020063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '71c3b5630fbe'
down_revision: Union[str, None] = '68c1ac4ab3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if the constraint exists before dropping it
    try:
        op.drop_constraint('cart_ibfk_1', 'cart', type_='foreignkey')
    except:
        pass  # Constraint might not exist
    
    # Then alter the column to NOT NULL
    op.alter_column('cart', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    
    # Create new foreign key constraint without SET NULL
    op.create_foreign_key(None, 'cart', 'products', ['product_id'], ['id'])
    
    # Handle guest table indexes with try-catch
    try:
        op.drop_index('guest_id', table_name='guests')
    except:
        pass
    try:
        op.drop_index('ix_guests_guest_id', table_name='guests')
    except:
        pass
    op.create_index(op.f('ix_guests_guest_id'), 'guests', ['guest_id'], unique=True)
    op.add_column('orders', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('order_status', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('shipping_address', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'])
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'status')
    # These columns are already added in d83a2adaaacb, so we just need to alter them if needed
    # op.add_column('transactions', sa.Column('reference', sa.String(length=255), nullable=False))
    # op.add_column('transactions', sa.Column('currency', sa.String(length=10), nullable=False))
    # op.add_column('transactions', sa.Column('channel', sa.String(length=50), nullable=True))
    # op.add_column('transactions', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('transactions', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=False)
    op.drop_constraint('transactions_ibfk_2', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'transaction_type')
    op.drop_column('transactions', 'user_id')
    
    # Handle user table indexes with try-catch
    try:
        op.drop_index('email', table_name='users')
    except:
        pass
    try:
        op.drop_index('username', table_name='users')
    except:
        pass
    try:
        op.drop_index('ix_users_email', table_name='users')
    except:
        pass
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    try:
        op.drop_index('ix_users_username', table_name='users')
    except:
        pass
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('username', 'users', ['username'], unique=False)
    op.create_index('email', 'users', ['email'], unique=False)
    op.add_column('transactions', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('transaction_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.create_foreign_key('transactions_ibfk_2', 'transactions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.alter_column('transactions', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('transactions', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('transactions', 'paid_at')
    op.drop_column('transactions', 'channel')
    op.drop_column('transactions', 'currency')
    op.drop_column('transactions', 'reference')
    op.add_column('orders', sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.add_column('orders', sa.Column('total_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'order_status')
    op.drop_column('orders', 'unit_price')
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'amount')
    op.drop_column('orders', 'product_id')
    op.drop_index(op.f('ix_guests_guest_id'), table_name='guests')
    op.create_index('ix_guests_guest_id', 'guests', ['guest_id'], unique=False)
    op.create_index('guest_id', 'guests', ['guest_id'], unique=False)
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_ibfk_1', 'cart', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.alter_column('cart', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
