"""make transaction reference required and remove nullable

Revision ID: 72440580f513
Revises: d83a2adaaacb
Create Date: 2026-03-08 04:24:57.152910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '72440580f513'
down_revision: Union[str, None] = 'd83a2adaaacb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'reference',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.drop_index('reference', table_name='transactions')
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.create_index('reference', 'transactions', ['reference'], unique=False)
    op.alter_column('transactions', 'reference',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    # ### end Alembic commands ###
