"""fix cart table constraints

Revision ID: 89dd00b0856f
Revises: 71c3b5630fbe
Create Date: 2026-03-09 19:03:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '89dd00b0856f'
down_revision: Union[str, None] = '71c3b5630fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, let's check if there are any NULL values in product_id and update them
    op.execute("UPDATE cart SET product_id = 0 WHERE product_id IS NULL")
    
    # Drop the existing foreign key constraint if it exists
    try:
        op.drop_constraint('cart_ibfk_1', 'cart', type_='foreignkey')
    except:
        pass
    
    # Make product_id NOT NULL
    op.alter_column('cart', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    
    # Create new foreign key constraint
    op.create_foreign_key('cart_ibfk_1', 'cart', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_ibfk_1', 'cart', type_='foreignkey')
    op.alter_column('cart', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key('cart_ibfk_1', 'cart', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
