"""Add is_deleted to products and status enum to users

Revision ID: a1b2c3d4e5f6
Revises: 8eaaa36975b8
Create Date: 2026-03-09 12:31:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '8eaaa36975b8'
branch_labels: Union[str, None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    
    # Create enum type
    user_status_enum = sa.Enum('active', 'inactive', 'suspended', name='user_status')
    user_status_enum.create(op.get_bind())
    
    # Add status column to users table
    op.add_column('users', sa.Column('status', user_status_enum, nullable=False, server_default='active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('products', 'is_deleted')
    sa.Enum(name='user_status').drop(op.get_bind())
    # ### end Alembic commands ###
