"""add payment fields to transactions

Revision ID: bd92216c1a5b
Revises: f8c2d4e5a6b7
Create Date: 2026-03-08 07:26:19.425160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bd92216c1a5b'
down_revision: Union[str, None] = 'f8c2d4e5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('reference', sa.String(length=255), nullable=True))
    op.add_column('transactions', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('transactions', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('transactions', sa.Column('provider', sa.String(length=50), nullable=False))
    op.add_column('transactions', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['reference'])
    op.drop_column('transactions', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'paid_at')
    op.drop_column('transactions', 'provider')
    op.drop_column('transactions', 'status')
    op.drop_column('transactions', 'amount')
    op.drop_column('transactions', 'reference')
    # ### end Alembic commands ###
