"""add paystack fields to transactions

Revision ID: d83a2adaaacb
Revises: f8c2d4e5a6b7
Create Date: 2026-03-08 02:49:01.963305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd83a2adaaacb'
down_revision: Union[str, None] = 'f8c2d4e5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('reference', sa.String(length=255), nullable=True))
    op.add_column('transactions', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('transactions', sa.Column('channel', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['reference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'paid_at')
    op.drop_column('transactions', 'channel')
    op.drop_column('transactions', 'currency')
    op.drop_column('transactions', 'reference')
    # ### end Alembic commands ###
